### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by leejaeseung** [leejaeseung/medical_survey_app#2]
- [x] 설문 제출 레이아웃
- [x] 직업 사항 레이아웃
- [x] 설문 제출 데이터 저장
- [ ] 직업 사항 데이터 저장
- [x] 설문 제출 데이터 유효성 검사
- [ ] 직업 사항 데이터 유효성 검사
- [x] 유효성 모달 창 제작
